# Generated by Django 2.1.5 on 2019-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdminLite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('chassisno', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('date_of_sales_letter', models.DateTimeField()),
                ('month_and_year_manufacture', models.DateTimeField()),
                ('aadhar_pdf', models.FileField(blank=True, upload_to='aadhar')),
                ('initial_form_pdf', models.FileField(blank=True, upload_to='form')),
                ('tax_reciept_pdf', models.FileField(blank=True, upload_to='tax_reciept')),
                ('insurance_pdf', models.FileField(blank=True, upload_to='insurance')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
