# Generated by Django 2.0.1 on 2019-10-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdminLite', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_sales_letter',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='month_and_year_manufacture',
            field=models.DateField(verbose_name='YYYYMM'),
        ),
    ]
